# - name: "Print all available facts"
#   ansible.builtin.debug:
#     var: ansible_facts

- name: Set timezone to Moscow
  become: true
  community.general.timezone:
    name: Europe/Moscow

# - name: "Set current time"
#   become: true
#   ansible.builtin.command: 'date --set="{{ current_datetime }}"' 
  


- name: "Install NTP package"
  ansible.builtin.apt:
    name: "ntp"
    state: "latest"
    update_cache: true 

- name: "Copy the ntp.conf template file"
  template: "src=ntp.conf.j2 dest=/etc/ntpsec/ntp.conf"

