
  # Main NGINX tasks

- name: "Output OS Family" 
  ansible.builtin.debug:
    msg: OS family {{ ansible_os_family }}

- name: "Ubuntu Tasks"
  include_tasks: "ubuntu.yml"
  when: ansible_os_family == "Debian"

- name: "CentOS Tasks"
  include_tasks: "centos.yml"
  when: ansible_os_family == "RedHat"
