---
- name: "Test jinja"
  hosts: centos
  tasks:
  - name: "Generate jinja"
    vars:
      servers:
      - sname: ranger
        software:
        - ntp
        - nginx
        - http
      - sname: ranger
        software:
        - postgres
        - mysql
      - sname: hunter
        software:
        - webapp
        - loader
        calls:
          name: arg1
          values:
          - run_main
          - run_schedule
    ansible.builtin.template:
      src: test_jinja.j2
      dest: /home/wakh/test.jinja
      owner: wakh
      group: wakh
      mode: '0644'