- 
  name: Test connection to Linux targets
  hosts: linux
  tasks:
    - name: Ping test
      ping:
- 
  name: Test connection to Windows targets
  hosts: ungrouped
  tasks:
    - name: Ping test
      win_ping:
