
  # Installing NGINX

- name: "Install Nginx via APT"
  ansible.builtin.apt:
    name: "nginx"
    state: "latest"
    update_cache: true 
- name: "Delete /var/www/html folder"
  ansible.builtin.file:
    path: "/var/www/html"
    state: "absent"

- name: "Copy out html to /var/www/html folder"
  ansible.builtin.copy:
    src: "files/html2/"
    dest: "/var/www/html/"
    owner: "wakh"
    group: "wakh"
    mode: "0644"