# Installing MySQL

- name: "Install MySQL via APT"
  ansible.builtin.apt:
    name: "mysql-server"
    state: "latest"
    update_cache: true 


- name: "Install pyMySQL via APT"
  ansible.builtin.apt:
    name: "python3-PyMySQL"
    state: "latest"
    update_cache: true 

- name: "Set up root user"
  community.mysql.mysql_user:
    name: "root"
    password: "P@ssw0rd"
    login_user: "root"
    login_password: "P@ssw0rd"
    check_implicit_admin: true 
    login_unix_socket: "/var/run/mysqld/mysqld.sock"

- name: "Remove anonymous users"
  community.mysql.mysql_user:
    name: ""
    state: "absent"
    login_user: "root"
    login_password: "P@ssw0rd"

- name: "Remove test DB"
  community.mysql.mysql_db:
    name: "test"
    state: "absent"
    login_user: "root"
    login_password: "P@ssw0rd"