
  # Installing NGINX

- name: "Install Nginx via DNF"
  ansible.builtin.dnf:
    name: "nginx"
    state: "latest"
    update_cache: true 
    
- name: "Enable service Nginx and ensure it is not masked"
  ansible.builtin.systemd_service:
    name: "nginx"
    enabled: true
    masked: no

- name: "Delete /usr/share/nginx/html folder"
  ansible.builtin.file:
    path: "/usr/share/nginx/html"
    state: "absent"

- name: "Copy out html to /usr/share/nginx/html folder"
  ansible.builtin.copy:
    src: "files/html"
    dest: "/usr/share/nginx"
    owner: "nginx"
    group: "nginx"
    mode: "0644"

- name: "permanently enable http service, also enable it immediately if possible"
  ansible.posix.firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: true
    offline: true