- name: "Check PHP version"
  ansible.builtin.fail:
    msg: "The php of {{ php_version }} doesn't exist"
  when: php_version > 9.0

- name: "Add REPO for php"
  ansible.builtin.apt_repository:
    repo: 'ppa:ondrej/php'
    update_cache: true

- name: "Installing php fpm and php mysql"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "latest"
    update_cache: true
  with_items:
    - "php{{ php_version }}-fpm"
    - "php{{ php_version }}-mysql"
  
- name: "Check the nginx directory existence"
  ansible.builtin.stat:
    path: "/etc/nginx/sites-available"
  register: php_sites_available_stats

- name: "Show php_sites_result"
  ansible.builtin.debug:
    var:  php_sites_available_stats

- name: "Copy php files to /var/www/ folder"
  ansible.builtin.copy:
    src: "files/test-php/php_test"
    dest: "/var/www/"
    owner: "wakh"
    group: "wakh"
    mode: "0644"
  when: php_sites_available_stats.stat.exists


- name: "Copy config Nginx for php test"
  ansible.builtin.template:
    src: "nginx.conf.j2" 
    dest: "/etc/nginx/sites-available/php_test.conf"
    owner: "wakh"
    group: "wakh"
    mode: "0644"
  when: php_sites_available_stats.stat.exists

- name: "Create symlink for site in nginx"
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/php_test.conf"
    dest: "/etc/nginx/sites-enabled/php_test.conf"
    state: "link"
  when: php_sites_available_stats.stat.exists
