#################
# LEMP Playbook #
#################
---
- hosts: "sav-ansible-slurm-01"
  become: true
  roles:
  - main
  - nginx  
  - mysql
  - php
  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
    - name: "Reload nginx"
      ansible.builtin.service:
        name: "nginx"
        state: "reloaded"
    
    - name: "Reload ntp"
      ansible.builtin.service:
        name: "ntpsec"
        state: "restarted"


  



  


  