#################
# LEMP CHECK PLAYBOOK WITH PHP/MYSQL #
#################
---
- name: Verify
  hosts: 'all,!default'
  gather_facts: false
  tasks:

    - name: Checking if website is available and has contents locally
      ansible.builtin.uri:
        url: http://localhost
        method: GET
        status_code: 200
        return_content: true
      register: local_contents
      failed_when: "local_contents.status != 200"

- name: remotecheck
  hosts: 'all,!default'
  connection: local
  gather_facts: false
  tasks:

    - name: Checking if website is available and has contents
      ansible.builtin.uri:
        url: "http://{{ item }}/test-connection.php"
        method: GET
        status_code: 200
        return_content: true
      register: remote_contents
      failed_when: "remote_contents.status != 200 or 'VERSION' not in remote_contents.content"
      with_items:
        - "{{ hostvars[inventory_hostname].ansible_host }}"
